spring:
  application:
    name: orchestrator
  profiles:
    default: dev
  jackson:
    default-property-inclusion: non_null
management:
  endpoints:
    web:
      exposure:
        include: health, shutdown, refresh
  endpoint:
    shutdown:
      enabled: true
    startup:
      enabled: true
server:
  port: 9001
blockchain:
  besu:
    channel: mychannel
    chaincodeName: opendid
    chainId: 1337
    gasLimit: 10000000
    gasPrice: 0
    connectionTimeout: 10000
  ledgerService:
    port: 8098
    jarPath: /jars
    file: did-ledger-service-server-1.0.1.jar
database:
  port: 5430
  user: omn
  password: omn
  db: omn
services:
  cliToolPath: /tool
  jarPath: /jars
  walletPath: /wallet
  didDocPath: /DIDDoc
  logPath: /logs
  server:
    tas:
      name: TA
      port: 8090
      file: did-ta-server-1.0.1.jar
    issuer:
      name: Issuer
      port: 8091
      file: did-issuer-server-1.0.1.jar
    verifier:
      name: Verifier
      port: 8092
      file: did-verifier-server-1.0.1.jar
    api:
      name: API
      port: 8093
      file: did-api-server-1.0.1.jar
    cas:
      name: CA
      port: 8094
      file: did-ca-server-1.0.1.jar
    wallet:
      name: Wallet
      port: 8095
      file: did-wallet-server-1.0.1.jar
    demo:
      name: Demo
      port: 8099
      file: did-demo-server-1.0.1.jar
generator:
  easySettingModeEnabled: true
logging:
  level:
    org.omnione: debug
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: ASC
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
